# Generated by Django 6.0.6 on 2026-07-01 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='knowledge_docs/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('csv', 'CSV')], max_length=10)),
                ('topic', models.CharField(choices=[('returns', 'Returns & Refunds'), ('delivery', 'Delivery & Shipping'), ('payments', 'Payments'), ('warranty', 'Warranty'), ('products', 'Products'), ('orders', 'Orders'), ('store_info', 'Store Information'), ('promotions', 'Promotions'), ('support', 'Support Scripts'), ('general', 'General FAQ')], default='general', max_length=20)),
                ('policy_version', models.CharField(blank=True, max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_docs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'db_table': 'knowledge_chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='RAGRetrievalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(blank=True, null=True)),
                ('query_text', models.TextField()),
                ('filters_used', models.JSONField(default=dict)),
                ('retrieved_chunk_ids', models.JSONField(default=list)),
                ('similarity_scores', models.JSONField(default=list)),
                ('selected_chunk_ids', models.JSONField(default=list)),
                ('verification_result', models.BooleanField(default=False)),
                ('confidence_band', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_logs', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'rag_retrieval_logs',
            },
        ),
    ]
