# Generated by Django 6.0.6 on 2026-07-01 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('validate_input', 'Validate Input'), ('detect_intent', 'Detect Intent'), ('check_missing_fields', 'Check Missing Fields'), ('create_plan', 'Create Plan'), ('select_tool', 'Select Tool'), ('execute_tool', 'Execute Tool'), ('verify_result', 'Verify Result'), ('generate_response', 'Generate Response'), ('safety_check', 'Safety Check'), ('route_handover', 'Route to Handover'), ('route_clarification', 'Route to Clarification'), ('route_answer', 'Route to Answer')], max_length=50)),
                ('tool_name', models.CharField(blank=True, max_length=50)),
                ('tool_input', models.JSONField(default=dict)),
                ('tool_output', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('confidence_at_action', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_actions', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'agent_actions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50)),
                ('error_type', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('retry_attempted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_errors', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'tool_errors',
            },
        ),
    ]
