# Generated by Django 6.0.6 on 2026-07-01 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('AI_ACTIVE', 'AI Active'), ('WAITING_FOR_STAFF', 'Waiting for Staff'), ('HUMAN_ACTIVE', 'Human Active'), ('RESOLVED', 'Resolved')], default='AI_ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_given', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('ai', 'AI'), ('staff', 'Staff'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('quick_replies', models.JSONField(blank=True, default=list)),
                ('is_internal_note', models.BooleanField(default=False)),
                ('message_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intents', models.JSONField(default=list)),
                ('customer_goal', models.TextField(blank=True)),
                ('entities', models.JSONField(default=dict)),
                ('missing_fields', models.JSONField(default=list)),
                ('clarification_attempts', models.PositiveIntegerField(default=0)),
                ('planned_steps', models.JSONField(default=list)),
                ('completed_steps', models.JSONField(default=list)),
                ('tool_call_count', models.PositiveIntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_state', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'conversation_states',
            },
        ),
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('positive', 'Thumbs Up'), ('negative', 'Thumbs Down')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('support_type', models.CharField(choices=[('AI_ONLY', 'AI Only'), ('AI_AND_HUMAN', 'AI + Human'), ('HUMAN_ONLY', 'Human Only')], max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'customer_feedback',
            },
        ),
    ]
