# Generated by Django 6.0.6 on 2026-07-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='pending_handover_reason',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
