# Generated by Django 6.0.6 on 2026-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversationstate_pending_handover_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='order_lookup_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
