# Generated by Django 6.0.6 on 2026-07-01 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_reason', models.CharField(choices=[('explicit_request', 'Customer Requested'), ('low_confidence', 'Low AI Confidence'), ('no_evidence', 'No Evidence Found'), ('tool_failure', 'Tool Failure'), ('repeated_failure', 'Repeated Failure'), ('sensitive_issue', 'Sensitive Issue'), ('clarification_failed', 'Clarification Failed')], max_length=25)),
                ('ai_summary', models.TextField(blank=True)),
                ('customer_goal', models.TextField(blank=True)),
                ('detected_intents', models.JSONField(default=list)),
                ('detected_entities', models.JSONField(default=dict)),
                ('tools_used', models.JSONField(default=list)),
                ('rag_sources', models.JSONField(default=list)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('suggested_action', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_case', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'support_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='staff.supportcase')),
            ],
            options={
                'db_table': 'staff_notes',
                'ordering': ['created_at'],
            },
        ),
    ]
