# Generated by Django 6.0.6 on 2026-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcase',
            name='handover_reason',
            field=models.CharField(choices=[('explicit_request', 'Customer Requested'), ('low_confidence', 'Low AI Confidence'), ('no_evidence', 'No Evidence Found'), ('tool_failure', 'Tool Failure'), ('repeated_failure', 'Repeated Failure'), ('sensitive_issue', 'Sensitive Issue'), ('clarification_failed', 'Clarification Failed'), ('frustrated_customer', 'Frustrated Customer')], max_length=25),
        ),
    ]
